# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ahnaf
tagline:          'Portfolio'
description:      ''
url:              http://github.com/ahnasfasifkhan/ahnafasifkhan.github.io
baseurl:          /

author:
  name:           'Ahnaf Asif Khan'
  url:            http://github.com/ahnasfasifkhan

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           http://github.com/ahnafasifkhan
